live_config_reload = true

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "Monaspace Argon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Argon"
style = "Italic"

[font.normal]
family = "Monaspace Argon"
style = "Regular"

[[keyboard.bindings]]
chars = " sf"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = " sg"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015b"
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015d"
key = "RBracket"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 1
option_as_alt = "Both"

[window.padding]
x = 20
y = 20
